### ISSUE TITLE
MIDI callback functions for CCreceive (or more clear examples)

### ISSUE THREAD

**Issue by jsr606** [dennisppaul/wellen#15]
this is how the MIDIbus library handles the callbacks

```
void noteOn(Note note) {
  // Receive a noteOn
  println();
  println("Note On:");
  println("--------");
  println("Channel:"+note.channel());
  println("Pitch:"+note.pitch());
  println("Velocity:"+note.velocity());
}

void noteOff(Note note) {
  // Receive a noteOff
  println();
  println("Note Off:");
  println("--------");
  println("Channel:"+note.channel());
  println("Pitch:"+note.pitch());
  println("Velocity:"+note.velocity());
}

void controllerChange(ControlChange change) {
  // Receive a controllerChange
  println();
  println("Controller Change:");
  println("--------");
  println("Channel:"+change.channel());
  println("Number:"+change.number());
  println("Value:"+change.value());
}

```

**Comment by dennisppaul** [comment]
i like the idea of having the option have these convinience methods (i.e `midi_note_on(channel, note, velocity)`, `midi_note_off(channel, note, velocity(?))`, `midi_cc(channel, number, value)` ). 

maybe also the midi clock? currently those MIDI clock events are received:

```
void clock_tick();
void clock_start();
void clock_continue();
void clock_stop();
void clock_song_position_pointer(int pOffset16th);
```

right now everything ( OSC and MIDI ) goes through `event_receive(int, float[])`.

**Comment by jsr606** [comment]
yes, having a callback for MIDI transport / timecode related messages would be super useful too!

**Comment by dennisppaul** [comment]
added methods `midi_note_on(channel, note, velocity)`, `midi_note_off(channel, note)` and `midi_control_change(channel, number, value)`. todo(add `clock_*` + `program_change`)

**Comment by dennisppaul** [comment]
@jsr606 check `ExampleExternal03MIDIExternalKeyboard` for implementation example

**Comment by dennisppaul** [comment]
added methods `midi_program_change(channel, number, value)`, `midi_clock_tick()`, `midi_clock_start()`, `midi_clock_continue()`, `midi_clock_stop()`, `midi_clock_song_position_pointer(offset)`
