### ISSUE TITLE
noteOn duration in ms

### ISSUE THREAD

**Issue by jsr606** [dennisppaul/wellen#16]
right now the duration for tones are set in seconds. perhaps milliseconds make more sense?

**Comment by dennisppaul** [comment]
i d vote against it. all times are spec'd in seconds all across the library. maybe a util method like `to_sec(int millis)` would help to make the matter more explicit in code.

**Comment by dennisppaul** [comment]
added `to_sec(int pMilliSeconds)` and `to_millis(float pSeconds)` to `Wellen`. now `Tone.note_on(48, 85, to_sec(500))` allows to specify time in milliseconds.
