### ISSUE TITLE
Example for InstrumentInternalLibrary please

### ISSUE THREAD

**Issue by purplesquircle** [dennisppaul/wellen#18]
I'm using Wellen to create generative music based on the Mizmaze turf labyrinth near Winchester in the UK. The project is going well - but I can't figure out how to use your new InstrumentInternalLibrary functions - specifically BELL. I'm a novice programmer and mainly figure things out by looking at examples. I've tried Tone.replace_instrument(InstrumentInternalLibrary.BELL) but get the error "InstrumentInternalLibrary.BELL cannot be resolved to a variable". It would be great if you could include an example for this when you publish the next release - thanks.

**Comment by dennisppaul** [comment]
including instrument from the collection `InstrumentInternalLibrary` should work with `Tone.replace_instrument(new InstrumentInternalLibrary.BELL(int))`. if it does not there is a chance that your library is out of date. i suggest to download and use the latest built ZIP from under https://github.com/dennisppaul/wellen/blob/main/wellen.zip

there is an example in the `instruments` section that is called `ExampleInstruments08CustomDSPInstrument`. i have added the bell to the example.

**Comment by purplesquircle** [comment]
Thanks - that was all really helpful and I have that working now.

**Comment by dennisppaul** [comment]
great! i am happy to hear this.
